version: '3.7'

services:
    api-gateway:
        image: ratand/currex-api-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - '8765:8765'
        networks:
            - currency-network
        depends_on:
            - registry-server
            - rabbitmq
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://registry-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq

    currency-exchange:
        image: ratand/currex-currency-exchange-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - '8000:8000'
        networks:
            - currency-network
        depends_on:
            - registry-server
            - rabbitmq
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://registry-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq

    currency-conversion:
        image: ratand/currex-currency-conversion-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - '8100:8100'
        networks:
            - currency-network
        depends_on:
            - registry-server
            - currency-exchange
            - rabbitmq
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://registry-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq

    registry-server:
        image: ratand/currex-registry-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - '8761:8761'
        networks:
            - currency-network

    zipkin-server:
        image: openzipkin/zipkin:latest
        mem_limit: 300m
        ports:
            - '9411:9411'
        networks:
            - currency-network
        depends_on:
            - rabbitmq
        environment:
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        #Restart if there is a problem starting up
        restart: always

    rabbitmq:
        image: rabbitmq:3.8.12-management
        mem_limit: 300m
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - currency-network

networks:
    currency-network: